### ISSUE TITLE
Fetch modules only work if `version_select` is provided

### ISSUE THREAD

**Issue by onyxfish** [CJWorkbench/cjworkbench#131]
In order to make a new data loader I had to add this to my YAML config:

```yaml
- id_name: version_select
  type: custom
  name: Update
```

This should be in the docs.
